### ISSUE TITLE
JR18 Fresnel clipping with EPL

### ISSUE THREAD

**Issue by Jimbodiah** [post-kerbin-mining-corporation/FarFutureTechnologies#66]
When the JR18 is spawned on the completion of an EPL build, the nozzle part is clipped inside the EPL pad and other parts (causing the station to explode upon releasing the part (colliders of second ship become active inside first ship? and then RUD). 

There is also no surface attach possible to the last part of the frame prior to the nozzel, and the nozzle itself which may be why the part spawns inside the EPL pad?

![screen shot 01-08-18 at 06 53 pm](https://user-images.githubusercontent.com/16107012/34684539-b0ba115a-f4a5-11e7-9a28-0ca315ada6c1.JPG)

**Comment by ChrisAdderley** [comment]
So the no surface attach to the last part of the frame is intentional.... what I suspect is happening here is that EPL uses the drag cube sizes to decide what the actual "size" of the vessel is. 
It seems like the nozzle object will be moving after the cubes are recalculated for the segments, so might not be included in the calculation.
This will require some extensive investigation to confirm though. This post is mostly for my benefit so I remember what direction to go in.
  
 Oh, does this also happen with the beam core AM engine?

**Comment by Jimbodiah** [comment]
I will check that engine tonight.

**Comment by Jimbodiah** [comment]
That engine gets spawned a long way away from the EPL pad, but is still attached despite looking like it is floating free. I think it's because I have the short 6m version and the attach point is for the 30m long version.

![screen shot 01-09-18 at 09 30 pm](https://user-images.githubusercontent.com/16107012/34741894-86f3458c-f584-11e7-9b87-3dc1c8c96efd.JPG)

**Comment by ChrisAdderley** [comment]
As this engine also uses the length module, this fits well with the theory.
